name = 'Minimal TailwindCSS'
license = 'MIT'
licenselink = 'https://github.com/lubeso/hugo-themes-tailwindcss/LICENSE'
description = 'Minimal Hugo theme with TailwindCSS integration'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/lubeso/hugo-themes-tailwindcss'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# If the theme has a single author
[author]
  name = 'Luis Becerra Solis'
  homepage = 'www.lubeso.dev'

